security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
            
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain :
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    - { name: test, password: test, roles: 'ROLE_USER' }
        fos_userbundle:
            #id: fos_user.user_provider.username
            entity: { class: Acme\DemoBundle\Entity\User, property: username }

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: fos_user_security_login
                use_forward: true
                check_path: fos_user_security_check
                failure_path: /
                default_target_path: /
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/new, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/motdepasseoublier, role : "IS_AUTHENTICATED_ANONYMOUSLY" }
        - { path: ^/envoimotdepasseoubliee, role : "IS_AUTHENTICATED_ANONYMOUSLY" }
        - { path: ^/contact, role : "IS_AUTHENTICATED_ANONYMOUSLY" }